databases:
  - name: my_properties_pg_production
    user: chis

services:
  - type: web
    name: my_properties
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_properties_pg_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
