
default: &default
  adapter: postgresql
  encoding: unicode
  host: dpg-cgo819l269v5rjan6ocg-a
  port: 5432
  database: my_properties_pg_production
  username: chis
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_properties_pg_development

test:
  <<: *default
  database: my_properties_pg_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

