default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: '@Blanco23'
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: my_properties_development

test:
  <<: *default
  database: my_properties_test

production:
  <<: *default
  database: my_properties_production
